# Site settings
title: 只言片语 
header-img: img/home-bg.jpg
email: skybjf@126.com
keywords: 小久哥,只言片语,前端,前端工程师,前端程序员,程序猿,攻城狮,程序员,工程师,css,javascript,学习笔记,小久哥博客
description: "这是一个前端小菜鸟的博客~记录有关前端的一些小知识，学习笔记2015-7-23刚刚开通，还有很多不完善的地方需要一步步完善。"
baseurl: ""
url: "http://skybjf.github.io"
twitter_username: 陶远芝
github_username:  skybjf
facebook_username:  陶远芝
weibo_username: 很久很从前
zhihu_username: 小久哥

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM

author : 
  name : 小久哥
  email : skybjf@126.com